name: flutter_sdk
description: Supertonic Flutter SDK TTS Example
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.6.0
  args: ^2.4.0
  path_provider: ^2.1.1
  just_audio: ^0.10.5
  logger: ^2.0.2
  llama_cpp_dart: ^0.1.2+1
  dio: ^5.9.0
  crypto: ^3.0.7
  path: ^1.9.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/onnx/
    - assets/voice_styles/
    - assets/models/
  uses-material-design: true